### ISSUE TITLE
ff vs chrome table cell overflow

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-table#103]
consistency across browsers

![screen shot 2018-09-19 at 12 29 40 pm](https://user-images.githubusercontent.com/2789078/45767657-bf4c2980-bc08-11e8-8ff0-45631909ccc7.png)

**Comment by Marc-Andre-Rivet** [comment]
This behavior now seems to be the same in Chrome and FF

Chrome
![image](https://user-images.githubusercontent.com/8092993/64369997-77760c00-cfeb-11e9-901a-c77a44acee5b.png)

Firefox
![image](https://user-images.githubusercontent.com/8092993/64370006-7e9d1a00-cfeb-11e9-9fa1-122d190e7cc1.png)

**Comment by Marc-Andre-Rivet** [comment]
`td` and `th` both use `overflow-x: hidden` which apparently does not work in FF in this situation. Can change it to `overflow: hidden` which does work but we'll still run into issues with dropdowns as they **need** overflow to be visible in order for the dropdown to be displayed!

**Comment by chriddyp** [comment]
As far as I can tell from the updated documentation in http://dash.plotly.com/datatable/width, this is no longer an issue
