### ISSUE TITLE
Add dropdown flag to column + remove 'dropdown' column type

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-table#153]
With the addition of data types, using type 'dropdown' will become an issue as we'll probably be interested in the underlying data type of the column. We could add a flag like dropdown: true|false to denotate that instead of using the type or check all cells for a dropdown that applies to it. The 2nd approach would have a performance impact as all cells would need to be evaluated vs. the flag. I prefer having to set the flag explicitly.

Expected:
- update code so that ColumnType only accepts numeric and text
- add property dropdown: Boolean to column
- drive usage of dropdowns through the column dropdown property instead of the 'dropdown' type
existing tests pass

**Comment by alexcjohnson** [comment]
closed by https://github.com/plotly/dash-table/pull/329
