### ISSUE TITLE
Refactoring dropdown properties

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-table#156]
Similar to what's been done for styles, the dropdown properties need to be improved to provide a more cohesive API.

Existing props / sub-props
- column options
- column_static_dropdown and column_conditional_dropdown
- dropdown_properties

It's been established previously that:
- conditional and default dropdowns are required/useful for certain scenarios
- index based dropdowns are required/useful for certain scenarios

One approach would be to use the same "if" syntax as for styles (e.g. column_id="foo", row_index="123") to cover both use cases with a single property (or two properties, one for conditionals and one for base), getting rid of options and dropdown_properties and cleaning up both columns and getting rid of the untype-able prop.

This may lead to a "heavier" index based interface, which is or not acceptable. The goal here is both to implement a solution and to get the discussion started.

@cldougl @chriddyp

**Comment by alexcjohnson** [comment]
Done as of #446
