### ISSUE TITLE
support for numbers as widths

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#161]
in the JS inline-styles that the rest of the dash components support, `style={'width': 50}` works and is equivalent to `style={'width': '50px'}`. Our styles should be equivalent to this or at least raise an error if they aren't.

Note that there are some exceptions, like `lineHeight: 10` is actually a valid unit (it's not converted to `lineHeight: '10px'`)

**Comment by Marc-Andre-Rivet** [comment]
This works as described in `dash==1.2.0`, `dash-table==4.2.0`. Closing.
