### ISSUE TITLE
rename `fe` and `be` in pagination_mode?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#167]
- `fe` and `be` are too terse
- Many users aren't necessarily aware of the development terms "front-end" or "back-end"
- However, the name will need to refer to these concepts in some way
- Alternatives:
  - `client` / `server`
  - `browser` / `callback`
  - `frontend` / `backend`

**Comment by alexcjohnson** [comment]
`native` / `custom` FTW #446
