### ISSUE TITLE
next pass on dropdown API

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#168]
placeholder issue to discuss the next pass of the `column_conditonal_dropdown` property and friends.

In particular:
- `dropdown` inside the nested structure should be renamed to `options` to match `dcc.Dropdown`
- Similar to the `style` arguments, it would be nice if all of the dropdown properties had the same prefix, so something along the lines of `dropdown_by_row` or `dropdown_by_condition`
- The `clearable` property inside `columns` should be `dropdown_clearable` or perhaps under `dropdown_properties.clearable`
- Instead of `type: 'dropdown'`, maybe we should have `'type': 'enumerated'` and `'cell_renderer': 'dropdown'`
- A way to specify per-row dropdown options using row indicies or forthcoming row IDs

**Comment by alexcjohnson** [comment]
Closed - and then some - by #446
