### ISSUE TITLE
next pass at `content_style: 'fit' | 'grow'`

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#176]
Perhaps this behaviour can be integrated via a set of documented style parameters in the `style_table` property.

**Comment by chriddyp** [comment]
With the new defaults (`content_style: 'grow', style_table: {'width': '100%'}`), I found that I haven't needed to use `fit` yet. In fact, none of the examples in the docs use this.

**Comment by alexcjohnson** [comment]
🔪 in https://github.com/plotly/dash-table/pull/446 - though we missed it in the changelog and migration guide. Added to the changelog https://github.com/plotly/dash-table/commit/6721d03ae3bda1836ec157e097bdc4648b28bd59, migration guide edit to follow.
