### ISSUE TITLE
needs test - ability to create columns that don't have keys in the dataframe rows

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#20]
this way, a callback chain could be used to create _new_ columns
1 - callback 1 - create new columns
2 - callback 2 - fill out dataframe with new data of those columns

**Comment by Marc-Andre-Rivet** [comment]
There's already at least one test displaying a table with columns that do not match anything in the data. https://github.com/plotly/dash-table/blob/dev/tests/visual/percy-storybook/DashTable.percy.tsx#L52
