### ISSUE TITLE
Occasional cell height issue

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-table#214]
When resizing my window here https://dash.plot.ly/datatable/sizing I sometimes see this under "Overflow Strategies - Multiple Lines":

![image](https://user-images.githubusercontent.com/203523/47977288-363c6500-e085-11e8-95b5-9c12a01fd78d.png)

**Comment by Marc-Andre-Rivet** [comment]
Fixed by https://github.com/plotly/dash-table/pull/573. Closing.
