### ISSUE TITLE
update docs to show examples without double scrollbars

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-table#215]
In the docs here https://dash.plot.ly/datatable/sizing I see both horizontal and vertical doubled scrollbars:

![image](https://user-images.githubusercontent.com/203523/47977330-6be14e00-e085-11e8-8840-3791436a6858.png)
![image](https://user-images.githubusercontent.com/203523/47977338-78fe3d00-e085-11e8-9b11-7d4c7134df76.png)

**Comment by KMouratidis** [comment]
Same issue (?) on Chromium, Version 70.0.3538.77

Console inspection shows no errors. When highlighting the inner `div` with class `dash-spreadsheet-inner dash-spreadsheet dash-grow` only the first scrollbar is highlighted. The second is highlighted with the outer `div` with class `dash-spreadsheet dash-spreadsheet-container dash-grow`.

![image](https://user-images.githubusercontent.com/26832680/48633958-269a1600-e9cd-11e8-866e-8dbbe47160b6.png)

When opening the console I manually fiddle with the style (removing the `overflow-y: scroll;`), and it seems to solve it:

![image](https://user-images.githubusercontent.com/26832680/48634592-95c43a00-e9ce-11e8-8ad7-1d2ad30a73e7.png)

![image](https://user-images.githubusercontent.com/26832680/48634656-ba201680-e9ce-11e8-9b0e-32a9d29cd5e8.png)


Works fine on Firefox 63.0

![image](https://user-images.githubusercontent.com/26832680/48634070-6d880b80-e9cd-11e8-811e-dc1fbed25188.png)

**Comment by hearues-zueke-github** [comment]
I have also got the same issue like mentioned earlier.

On Linux in Chrome Version 68.0.3440.106 (Official Build) (64-bit) I am also getting horizontal and vertical double scrollbars. Here is also a comparison when I turn of the scrollbar manually:
![table_scroll](https://user-images.githubusercontent.com/7109889/48828222-741cd700-ed6f-11e8-88cd-4144acf09421.png)

Also on Linux in Firefox 63.0 (64-bit) I am getting the same issue too.
![table_scroll_firefox](https://user-images.githubusercontent.com/7109889/48828351-c6f68e80-ed6f-11e8-84a6-7f8562aeaeec.png)

The current fix in Chrome is also working in Firefox too.

Current versions on my PC:
```
Linux Ubuntu 18.04.1 LTS
plotly 3.4.1
dash_table 3.1.6
```

**Comment by vivekvs1** [comment]
Is there a fix to this bug yet? Thanks

**Comment by arpit-rajauria** [comment]
You can try below steps:
1. 'overflow-y': 'Scroll'  **to** 'overflow-y': 'auto'  & 'overflow-x': 'Scroll' **to** 'overflow-x': 'auto'
or 
1. 'overflowY': 'Scroll'  **to** 'overflowY': 'auto'  & 'overflowX': 'Scroll' **to** 'overflowX': 'auto'

2. Check if you are including any border in your table style code, if yes try removing it.
For example i **removed** this from style_table : **'border': 'thin lightgrey solid'** 

3. Check 'overflow-y':  & 'overflow-x':   in  "container"  style, try hiding them with "hidden"

I just started using dash.. i don't know the correct fix.. these steps resolved my issue so thought of sharing it.

**Comment by vivekvs1** [comment]
Hi Arpit,

Thanks for your suggestions. Making 'overflowY' 'auto', hides both the scrollbars. However for the case when I need the table to be scrollable,  its introducing two scrollbars. I tried changing the style of the containing Div to 'overflowY': hidden - but it doesn't seem to do anything. 

This to me appears to be a bug. Can someone confirm?

**Comment by vivekvs1** [comment]
One way to make this work is - instead of using 'overflow-y' as 'scroll', make 'virtualization' as 'True'

**Comment by imsrgadich** [comment]
```
html.Div([
    DataTable(....)
  ], 
style={
   "overflowX": "scroll",
   'height': 300},
   )
```
Adding style element in the Div solves the issue and gets rid of double scroll bars.

**Comment by QuentinDumont** [comment]
@imsrgadich , Thx man, I have been looking for a solution like this for a while.

**Comment by shengqiangzhang** [comment]
@imsrgadich 

Thanks,it solved the problem.

**Comment by om12nayak** [comment]
Issue fixed:-
 style_header=
                                {
                                    'fontWeight': 'bold',
                                    'border': 'thin lightgrey solid',
                                    'backgroundColor': 'rgb(100, 100, 100)',
                                    'color': 'white'
                                },
                                style_cell={
                                    'fontFamily': 'Open Sans',
                                    'textAlign': 'left',
                                    'width': '150px',
                                    'minWidth': '180px',
                                    'maxWidth': '180px',
                                    'whiteSpace': 'no-wrap',
                                    'overflow': 'hidden',
                                    'textOverflow': 'ellipsis',
                                    'backgroundColor': 'Rgb(230,230,250)'
                                },
                                style_data_conditional=[
                                    {
                                        'if': {'row_index': 'odd'},
                                        'backgroundColor': 'rgb(248, 248, 248)'
                                    },
                                    {
                                        'if': {'column_id': 'country'},
                                        'backgroundColor': 'rgb(255, 255, 255)',
                                        'color': 'black',
                                        'fontWeight': 'bold',
                                        'textAlign': 'center'
                                    }
                                ],
                                fixed_rows={'headers': True, 'data': 0}

**Comment by chriddyp** [comment]
This should be fixed now.

**Comment by amarvin** [comment]
I got the same error today with `dash-table==4.11.3` using `style_table={"overflowX": "Scroll"}` (as recommended by the docs). Switching to `style_table={"overflowX": "auto"}` removed the second scroll bar.
