### ISSUE TITLE
Table dropdown fields don't display with bootstrap 4.1

### ISSUE THREAD

**Issue by eddy-ojb** [plotly/dash-table#221]
This is an excellent addition to Dash - thank you all for the great work.

I have noticed a bug when using bootstrap 4.1 with Dash Datatables 3.1.2, which is that the dropdown fields do not display. I have identified that the dropdown css is possibly inheriting from bootstrap css and showing as 'display: hidden', rather than 'display: block', as illustrated in the image below:

![dash_dropdown_hidden](https://user-images.githubusercontent.com/26047714/48024064-82e07880-e137-11e8-831b-e648cbc6d8a7.png)

![dash_dropdown_block](https://user-images.githubusercontent.com/26047714/48024072-87a52c80-e137-11e8-91f0-325c24eb7864.png)

Whilst I don't expect you to support bootstrap css, I am not sure how I override this setting as it appears to be embedded within the cell html style properties.

**Comment by eddy-ojb** [comment]
I copied and pasted your code example, including the bootstrap version, and also made sure css was loaded from source. I have just tried it in Edge, Chrome and Firefox on Windows and all show the same behavior. I take it that this just works for your team... this is odd.

Dash package versions are:

```
dash                      0.28.6                    <pip>
dash-core-components      0.36.0                    <pip>
dash-html-components      0.13.2                    <pip>
dash-renderer             0.14.3                    <pip>
dash-table                3.1.2                     <pip>
```

![dash_dropdown_broken](https://user-images.githubusercontent.com/26047714/48025465-65151280-e13b-11e8-9f7e-87b714c26ac3.png)

**Comment by eddy-ojb** [comment]
Also, if I delete bootstrap from the <head> it works fine.

**Comment by chriddyp** [comment]
> I copied and pasted your code example, including the bootstrap version, and also made sure css was loaded from source. I have just tried it in Edge, Chrome and Firefox on Windows and all show the same behavior. I take it that this just works for your team... this is odd.

I actually didn't test my code snippet yet, I just wanted to make sure that it matched your environment before we started digging in. So, if that code snippet looks representative to you, then we'll look into it!

**Comment by eddy-ojb** [comment]
I see that this hasn't been assigned categories yet. Having done a bit more digging, I suppose it is a react-select issue of not being specific for the Select-menu-outer element. Would you like me to ask over on their github to assign more specific properties?

I realise that bootstrap isn't everybodies cup of tea and that it undoes what react seems to address, but my team has found it invaluable. I personally don't think bootstrap is the future but that building react compoments is, but i am loathe to stop using Bootstrap, given that it saves our team so much time in producing nice, responsive Dash UIs quickly.

**Comment by Motta23** [comment]
Any news around this? Or way you have bypassed the issue @eddy-ojb?

**Comment by jakhtar4299** [comment]
I worked around by adding the following to my CSS:

.Select-menu-outer {
    display : block !important;
}

**Comment by eddy-ojb** [comment]
Closing the issue as a css based solution has been implemented, thanks @jakhtar4299

**Comment by fingoldo** [comment]
Can someone look into this please. With current versions of dash and dash-bootstrap-components, css fix is not working anymore.

**Comment by shenshan** [comment]
css fix does not work for me either, any other suggestions?

**Comment by reesehopkins** [comment]
This worked for me: 

```python
dash_table.DataTable(
    id="id",
    columns=[
        {"name": "col-1", "id": "col1", "presentation": "dropdown"},
        {"name": "col-2", "id": "col2", "type": "numeric",},
    ],
    data=[],
    editable=True,
    row_deletable=True,
    css=[{"selector": ".Select-menu-outer", "rule": "display: block !important"}],
)
```

**Comment by shenshan** [comment]
Hi @reesehopkins, thank you so much! It now works for me. I found out that if I turn on some of the style arguments of the DataTable, it does not show up. For example, `style_cell={'overflow': hidden}`

**Comment by joaoheron** [comment]
Thank you both @shenshan and @reesehopkins . I could only be able to fix my issues based on your comments
