### ISSUE TITLE
Upgrade component toolchain for dash-table to match `dash-component-boilerplate`

### ISSUE THREAD

**Issue by notatallshaw** [plotly/dash-table#228]
Currently when I use Dash Table in Pycharm it tells me the module dash_table has no attribute DataTable. It seems this is because everything is dynamically loaded, it makes it a lot more difficult to work with compared to other Dash Components.

**Comment by chriddyp** [comment]
In fact, we already do this in our other component libraries. We just need to upgrade the toolchain to match the enhancements we made in https://github.com/plotly/dash-component-boilerplate

**Comment by T4rk1n** [comment]
Had a quick look, generating the components classes is mostly just changing `__init__.py` and the `build:py` command. I can make a PR for that.

For the dev bundle, I will need @Marc-Andre-Rivet help, the webpack configs are really different.

**Comment by T4rk1n** [comment]
Changed the component loading to generated classes in #243
