### ISSUE TITLE
The gridded view is invalid in IE11 and Edge

### ISSUE THREAD

**Issue by sylvoslee** [plotly/dash-table#230]

**Comment by chriddyp** [comment]
@sylvoslee - could you provide some more info? A screenshot, what in particular is invalid, etc?

**Comment by sylvoslee** [comment]
chrome:
![chrome](https://user-images.githubusercontent.com/34852097/48167506-d7961600-e326-11e8-88cf-e5bbbee0515c.jpg)
edge:
![edge](https://user-images.githubusercontent.com/34852097/48167507-d82eac80-e326-11e8-954e-4f744ca61387.jpg)

**Comment by sylvoslee** [comment]
IE:
11.2248.14393.0
Edge:
Microsoft Edge 38.14393.2068.0
Microsoft EdgeHTML 14.14393

**Comment by chriddyp** [comment]
Thanks! Confirmed in IE11 as well
![image](https://user-images.githubusercontent.com/1280389/48171068-42643480-e2c8-11e8-9868-769604d7d676.png)

**Comment by sylvoslee** [comment]
will this issue be fixed？

**Comment by Marc-Andre-Rivet** [comment]
@sylvoslee This seems to be working fine with `v1.11`. Here's what I see in IE11:
![image](https://user-images.githubusercontent.com/8092993/79461174-cba28f00-7fc3-11ea-9b6f-a7e166b7fc97.png)
