### ISSUE TITLE
Feature request: Ability to remove table borders completely

### ISSUE THREAD

**Issue by oriolmirosa** [plotly/dash-table#231]
I'm trying to convert some tables that I rendered in my app through convoluted HTML into the new `DataTable`s, but in order to reproduce the format I need to get rid of some of the table borders and that doesn't seem possible right now. I have used `style_as_list_view` but that doesn't help me with the horizontal borders. Basically, I'm trying to style my table like this:

![image](https://user-images.githubusercontent.com/6955013/48148887-d4e4e380-e288-11e8-90e5-3533b540f8a1.png)

Just as there is the `style_as_list_view` flag, could there be one called something like `style_without_borders` so that we can then add borders as needed through normal cell styling?

If this is acceptable and with some guidance, I'm happy to submit a PR for this.

**Comment by oriolmirosa** [comment]
I'm trying to convert some tables that I rendered in my app through convoluted HTML into the new `DataTable`s, but in order to reproduce the format I need to get rid of some of the table borders and that doesn't seem possible right now. I have used `style_as_list_view` but that doesn't help me with the horizontal borders. Basically, I'm trying to style my table like this:

![image](https://user-images.githubusercontent.com/6955013/48148887-d4e4e380-e288-11e8-90e5-3533b540f8a1.png)

Just as there is the `style_as_list_view` flag, could there be one called something like `style_without_borders` so that we can then add borders as needed through normal cell styling?

If this is acceptable and with some guidance, I'm happy to submit a PR for this.

**Comment by chriddyp** [comment]
And just for reference, here's what the current `style_as_list_view` looks like:
![image](https://user-images.githubusercontent.com/1280389/48149607-889aa300-e28a-11e8-9dfb-770ca89966f7.png)

You might be able to use the `style_data` or `style_cell` property to override the default styles. Could you try that? You'll need to inspect-element to see the existing styles to understand how to override them. we're using `box-shadow` for borders, so you might be able to supply your own border-box as `none` or something like that.

**Comment by oriolmirosa** [comment]
Thanks, @chriddyp. I had been inspecting the elements and playing with the `style_cell` property unsuccessfully, but I was assuming that the `border` property was used for the borders, so I was quite confused. I just modified the `box-shadow` property in `style_cell` and everything looks as I want it to. I'll close the issue. Thanks again!

**Comment by chriddyp** [comment]
Awesome! Would you mind posting an example of what you ended up doing? That way anyone else searching this issue in the future can benefit :)

**Comment by oriolmirosa** [comment]
Sure! Here's what I did (they key element to get rid of the borders is the `boxShadow: '0 0'` in the `style_cell`:

```
dash_table.DataTable(
    columns=[{"name": i, "id": i} for i in dataframe.columns],
    data=dataframe.to_dict("rows"),
    style_cell={'fontFamily': 'sans-serif', 'fontSize': '12px', 'boxShadow': '0 0'},
    style_cell_conditional=[{
        'if': {'row_index': 'even'},
        'backgroundColor': '#F5F5F5'
    }] + [{
        'if': {'column_id': col},
        'fontWeight': 'bold'
    } for col in df_index_names],
    style_header={
        'backgroundColor': 'white',
        'fontWeight': 'bold',
        'borderBottom': '1px solid black'
    }
)
```

And the result, which can be compared with the table I started with (not using `DataTable` shown above):

![image](https://user-images.githubusercontent.com/6955013/48162751-ea1f3980-e2ab-11e8-8521-04b7789aff68.png)

**Comment by chriddyp** [comment]
Perfect, looks great, thank you!

**Comment by innominate227** [comment]
In dash 1.0.0 you now need to use to remove the borders

> style_data={ 'border': '0px' },

**Comment by EricNeville** [comment]
> In dash 1.0.0 you now need to use `style_data={ 'border': '0px' }, ` to remove the borders

In the example posted by @oriolmirosa , the borders are removed in the body, but this does not overwrite the border between the top row of the body and the header. In comparison it seems to me that when using 
`style_data={ 'border': '0px' }`
this overwrites the border of the header and you lose the bottom border of the header. Is there any way around this? i.e. can we removed borders in the body but still have the header borders?
