### ISSUE TITLE
bundle.js isn't in the npm distribution anymore?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#235]
In the latest version, the remote URL for the dash package isn't found:
![image](https://user-images.githubusercontent.com/1280389/48244474-f7275000-e3b3-11e8-94cc-516b64439d3e.png)

This URL is specified in the `external_url` key here:
https://github.com/plotly/dash-table/blob/10b80296a8577a3efae20f996e71c2917a4d7e51/dash_table/__init__.py#L35-L37

Indeed, looking at the package that got uploaded, the `dash_table` folder is no longer there:
![image](https://user-images.githubusercontent.com/1280389/48244507-1e7e1d00-e3b4-11e8-9bdc-2f267d99343c.png)

So, either `dash_table/bundle.js` needs to get put back _or_ the `external_url` needs to get update to the new directory: `https://unpkg.com/dash-table@3.1.4/lib/bundle.js`

Now, it would be good if it was the former, so that we're standard across our libraries and across our dash-component-boilerplate project. That way, changes that we make to the boilerplate, like adding dev and prod versions of the bundle (done here: https://github.com/plotly/dash-component-boilerplate/pull/8), can get easily incorporated into this project (related issue is https://github.com/plotly/dash-table/issues/228)

cc @Marc-Andre-Rivet and @valentijnnieman

**Comment by Marc-Andre-Rivet** [comment]
Sigh. I missed that one it seems..

Fwiw, if the package.json entry point is set correctly, we shouldn't have to pass the explicit path to unpckg for the default case. 

I fail to see why we don't just output to a static directory like lib/, dist/, etc. and to a static filename like bundle, bundle.min, bundle.dev -- this whole python-like sub-directory scheme seems pointless and requires bits of code to map folders sprinkled everywhere (python init, webpack config, package.json, etc.). Am I missing the point?

**Comment by chriddyp** [comment]
@Marc-Andre-Rivet - You are welcome to improve the system with a PR to dash and all of the accompanying packages :)

**Comment by chriddyp** [comment]
>requires bits of code to map folders sprinkled everywhere (python init, webpack config, package.json, etc.). Am I missing the point

FWIW, that's why we have a component boilerplate and why we try to standardize on a structure

**Comment by chriddyp** [comment]
> this whole python-like sub-directory scheme

The `dash_table` folder is what is included in the Python package. So, the `bundle.js` file needs to get included in there in order to be distributed.

![image](https://user-images.githubusercontent.com/1280389/48266840-a12bca00-e3fe-11e8-81cd-91e464ba4241.png)

So, since the bundle.js file is already in there, it made sense when I wrote this system (2 years ago!) for the NPM package to just reference the same file, rather than needing to keep another copy of the `bundle.js` in a separate `lib` folder.

**Comment by chriddyp** [comment]
> To be blunt, the preferred setup you are describing makes it hard to make a well-built, clean npm package.

If we want to have multiple bundles (since we _need_ to include it in `dash_table/` for distribution), then just change the unpkg URL in `__init__.py` to point to the new location of the bundle you've created.

**Comment by Marc-Andre-Rivet** [comment]
Made more constructive comments and suggestions here:
https://github.com/plotly/dash-component-boilerplate/issues/38

**Comment by T4rk1n** [comment]
> I fail to see why we don't just output to a static directory like lib/, dist/,

The bundles are included in the package folder because we use `pkgutil.get_data` to retrieve the files no matter how they were installed on the python environment. Putting them elsewhere would break dash.
