### ISSUE TITLE
Embedded links support

### ISSUE THREAD

**Issue by azhuchkov** [plotly/dash-table#236]
Now it seems not possible to insert `dcc.Link` inside a table cell. It produces error: `Objects are not valid as a React child (found: object with keys {props, type, namespace}).`

The use case: I have a bunch of time-series data and would like to map a page with analytics for each series, and each page is referred from the aggregated table located at the main page (multi-page Dash).

**Comment by Marc-Andre-Rivet** [comment]
@azhuchkov Thanks for your comment. Linking this issue to the existing hyperlink support issue #222 and closing as a duplicate.
