### ISSUE TITLE
allow html rendering in cells

### ISSUE THREAD

**Issue by sdementen** [plotly/dash-table#248]
I am desperately trying to add a line break (<br>) in a cell to display two strings one below the other in a cell.
I have read about the issue https://github.com/plotly/dash-table/issues/222 where chriddyp adds some perspective to the issue (different renderer, editing cells, etc).
However, for my basic use case, is there some temporary "hack" allowing to add a <br> (and other simple html rendering like bold, ...) ? could I do it through css ? I also tried with a `Div(["text1", Br(), "text2"])` but without success.

**Comment by pmajmudar** [comment]
Hey @sdementen - we had a similar issue - we wanted line breaks in text field.

I used CSS to 'hack' this, if your data has line breaks in, then you can style with:
```
style_data={'whiteSpace': 'pre-line'}
```
the `pre-line` respects line breaks it seems.

**Comment by sdementen** [comment]
works great! tx @pmajmudar 
for the record, the cell needs to contain "\n" and not "<br>" for line breaks

**Comment by Marc-Andre-Rivet** [comment]
@sdementen We indeed don't currently support textarea (for explicit multiline) or html content but it is something we have discussed. Linking to the data types epic #166.

**Comment by jdide** [comment]
Is this still open? I see it was linked to #166 , which is marked as closed.  I'm trying to render HTML text with partial formatting in a cell.  Something like

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do <span class='yellow-background'>eiusmod tempor incididunt</span> ut labore et dolore magna aliqua.

But, of course, the HTML is escaped by default.

**Comment by Marc-Andre-Rivet** [comment]
Markdown support was added in [Dash v1.8.0](https://dash.plot.ly/datatable/typing) and should support most html use-cases.
