### ISSUE TITLE
num issues with filter?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#252]
I recently started using the new '_DataTable_' function. I am trying to implement a simple conditional formatting applied to a column. My issue is with the '_style_data_conditional_' under the '_filter_': option. It looks like the _num()_ function rounds to the nearest integer not allowing us to applied <> to decimal numbers in the column. Is this correct? Any help is very much appreciated.

Many thanks

_Originally posted by @rbolado in https://github.com/plotly/dash-table/issues/169#issuecomment-440716388_

**Comment by Marc-Andre-Rivet** [comment]
No, you are correct to assume that this should work. It's currently parsed as an integer but the change is trivial (https://github.com/plotly/dash-table/blob/c031ca82ea26368b8b496f48dd56a1a5820fa493/src/core/syntax-tree/lexicon.ts#L47)

**Comment by Marc-Andre-Rivet** [comment]
#169

**Comment by rbolado** [comment]
Hi Marc-Andre-Rivet,

Does this means that there is a typo in (` return parseInt(value, 10);`) and now it will be fixed in the near future?

Many thanks,
Rufino

**Comment by pchalasani** [comment]
I've noticed this bug too and would like to see it fixed

**Comment by Marc-Andre-Rivet** [comment]
The `num` and `str` cast do not exist anymore in `dash-table>=4.0.0` (`dash>=1.0.0`). Casting is implicit when comparing values. Closing as moot.
