### ISSUE TITLE
ImportError: cannot import name '_explicitize_args'

### ISSUE THREAD

**Issue by mailbagrahul** [plotly/dash-table#265]
@chriddyp #error
I'm getting Import error when I run one of the examples of datatable. Could you please assist to get thru.

import dash
import dash_table
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

app = dash.Dash(__name__)

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict("rows"),
)

if __name__ == '__main__':
    app.run_server(debug=True)

![image](https://user-images.githubusercontent.com/15937179/49361790-a7c20000-f691-11e8-81f8-9db91e2e2de3.png)

**Comment by Marc-Andre-Rivet** [comment]
@mailbagrahul What version of Dash are you running?

**Comment by Marc-Andre-Rivet** [comment]
Someone having a similar issue -- updating versions did the trick.
https://community.plot.ly/t/error-importing-dash-table-cannot-import-name-explicitize-args/16394

**Comment by TomKenda** [comment]
**Hello, I just downloaded dash and I am still having the same issue.**

**When I am using the latest version of the packages and then I try to import ´dash_table´ I get this error :** 

`import dash_table
Traceback (most recent call last):

  File "<ipython-input-10-f48bca51a57b>", line 1, in <module>
    import dash_table

  File "C:\Users\tomk-\anaconda3\lib\site-packages\dash_table\__init__.py", line 18, in <module>
    from ._imports_ import *  # noqa: E402, F401, F403

  File "C:\Users\tomk-\anaconda3\lib\site-packages\dash_table\_imports_.py", line 1, in <module>
    from .DataTable import DataTable

  File "C:\Users\tomk-\anaconda3\lib\site-packages\dash_table\DataTable.py", line 3, in <module>
    from dash.development.base_component import Component, _explicitize_args

ImportError: cannot import name '_explicitize_args' from 'dash.development.base_component' (C:\Users\tomk-\anaconda3\lib\site-packages\dash\development\base_component.py)`


**The only way I manage to load the packages without problem is by installing those versions :** 

` !pip install dash==0.30.0

 !pip install dash-core-components==0.38.1

 !pip install dash-html-components==0.13.2

 !pip install dash-renderer==0.15.1

 !pip install dash-table==3.1.7`


**Is it normal that the newest version does not contain the rigth file ?**

**Comment by alexcjohnson** [comment]
@TomKenda those are extremely old package versions. Since `dash` v1.0, dash pins the versions of dcc, html, table, and renderer so the version should only be specified for `dash` itself.
