### ISSUE TITLE
Copy-paste on possible when the table is editable

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-table#276]
As originally mentioned in https://github.com/plotly/dash-table/issues/75#issuecomment-443948092.

> At the moment, copying from browser only seem to work when the table is editable.
> 
> As an example, I tried to copy the content of the cell "New Mexico" on the simple table at https://dash.plot.ly/datatable/, and nothing gets copied in the clipboard.

**Comment by andreapiso** [comment]
There are issues with editable tables as well but of different nature. It seems the cell can be copied only when "open for editing" . For example, taking as reference the table at https://dash.plot.ly/datatable/interactivity  this is what I am seeing:

- Select the text "Afghanistan" on the first cell and in doing so drag the mouse outside of the cell border to the right. This causes the cell's background to not become red -> Copying and pasting this text will not work. 

- Select the cell "Afghanistan", its background color becomes red. Now select the text "Albania" on the cell below, dragging the mouse outside of the cell. The cell containing "Afghanistan" still has background color, while Albania is white. Copying and pasting the text "Albania" will now produce "Afghanistan"

**Comment by Marc-Andre-Rivet** [comment]
@andreapiso Thanks for the additional feedback.

> Select the text "Afghanistan" on the first cell and in doing so drag the mouse outside of the cell border to the right. This causes the cell's background to not become red -> Copying and pasting this text will not work.

I think this would qualify as another issue -- for a feature improvement this time.

The table does not support dragging operations at the moment but it could be an interesting improvement in terms of usability. At the moment you have to either (1) click the first cell and shift click the last cell of the zone you want to select or (2) select a cell and shift+(arrow keys).

> Select the cell "Afghanistan", its background color becomes red. Now select the text "Albania" on the cell below, dragging the mouse outside of the cell. The cell containing "Afghanistan" still has background color, while Albania is white. Copying and pasting the text "Albania" will now produce "Afghanistan"

I think this qualifies as the same scenario as the first one above -- dragging operations don't mean anything to the table so the selection never changed. Copy/paste copies "Afghanistan" as expected.

I will let you create that one if you don't mind :)

**Comment by bjonen** [comment]
Copy paste of cell contents is not working for me with dash_table version 4.10.1. Also selecting/copying from the docs seems not to be possible (https://dash.plotly.com/datatable).
