### ISSUE TITLE
Header tooltips

### ISSUE THREAD

**Issue by eliasdabbas** [plotly/dash-table#295]
Naming columns can be easy, and can be difficult sometimes. Even when it is easy, we often need to explain a little more about the data in a certain column without having to clutter the page / table with too much text. 
A good solution to this might be to create the ability to add a clickable question mark (or some other symbol) which shows a tooltip explaining more about the column. 
Something like this: 

<img width="798" alt="screen shot 2018-12-12 at 1 01 02 am" src="https://user-images.githubusercontent.com/15708966/49836093-1e55b080-fdaa-11e8-8c35-0c0e48afade1.png">

Or maybe just hovering over a column name shows the optional tooltip: 

<img width="612" alt="screen shot 2018-12-12 at 1 08 11 am" src="https://user-images.githubusercontent.com/15708966/49836220-85736500-fdaa-11e8-9f18-a779252b3dc4.png">

Thanks!

**Comment by chriddyp** [comment]
Also important if the column header is cutoff with ellipses, as in our examples in https://dash.plotly.com/datatable/sizing

**Comment by Marc-Andre-Rivet** [comment]
Note: Remove `limitation` from https://dash.plotly.com/datatable/height (https://github.com/plotly/dash-docs/pull/847/files) once fixed

**Comment by fheilz** [comment]
@chriddyp Has this been added yet?

**Comment by chriddyp** [comment]
Not yet! But it is still a good idea. This issue will be updated when it is added. Alternatively, you can always check the CHANGELOG https://github.com/plotly/dash-table/blob/dev/CHANGELOG.md or search through closed PRs: https://github.com/plotly/dash-table/pulls?q=is%3Apr+is%3Aclosed

**Comment by Zylatis** [comment]
Looking forward to this feature!

**Comment by secsilm** [comment]
@Marc-Andre-Rivet I see this is closed. Could you please give a example how to use the new `tooltip_header` feature?
