### ISSUE TITLE
show page numbers for pagination

### ISSUE THREAD

**Issue by bwang2453** [plotly/dash-table#299]
Thanks for your interest in Plotly's Dash DataTable component!!

Note that GitHub issues in this repo are reserved for bug reports and feature
requests. Implementation questions should be discussed in our
[Dash Community Forum](https://community.plot.ly/c/dash).

Before opening a new issue, please search through existing issues (including
closed issues) and the [Dash Community Forum](https://community.plot.ly/c/dash).
If your problem or idea has not been addressed yet, feel free to
[open an issue](https://github.com/plotly/plotly.py/issues/new).

When reporting a bug, please include a reproducible example! We recommend using
the [latest version](https://github.com/plotly/dash-table/blob/master/CHANGELOG.md)
as this project is frequently updated. Issues can be browser-specific so
it's usually helpful to mention the browser and version that you are using.

Thanks for taking the time to help up improve this component!

**Comment by bwang2453** [comment]
Currently a paginated datatable only show "Previous" and "Next" buttons. Nobody knows which page is. It would be great to show the current page number and the total pages. 
Thanks!

**Comment by amarvin** [comment]
Adopting the view of react-bootstrap-table (http://allenfang.github.io/react-bootstrap-table/example.html#pagination) would be ideal, as it adds the page number info and improves the default styling to Bootstrap.

**Comment by apollonin** [comment]
Hi, are there any updates regarding this issue? It would be great to see current page number.

**Comment by threemonks** [comment]
Is this request on the feature list to be implemented? If not, would somebody able to provide some pointer such that it can be achieved with some temporary work around?

**Comment by Toxyl** [comment]
Besides that this a UX/UI flaw that should not have happened in the first place, when will this be implemented? I don't believe it takes over half a year to fix this...
