### ISSUE TITLE
filter a table between values

### ISSUE THREAD

**Issue by bwang2453** [plotly/dash-table#301]
Thanks for your interest in Plotly's Dash DataTable component!!

Note that GitHub issues in this repo are reserved for bug reports and feature
requests. Implementation questions should be discussed in our
[Dash Community Forum](https://community.plot.ly/c/dash).

Before opening a new issue, please search through existing issues (including
closed issues) and the [Dash Community Forum](https://community.plot.ly/c/dash).
If your problem or idea has not been addressed yet, feel free to
[open an issue](https://github.com/plotly/plotly.py/issues/new).

When reporting a bug, please include a reproducible example! We recommend using
the [latest version](https://github.com/plotly/dash-table/blob/master/CHANGELOG.md)
as this project is frequently updated. Issues can be browser-specific so
it's usually helpful to mention the browser and version that you are using.

Thanks for taking the time to help up improve this component!

**Comment by Marc-Andre-Rivet** [comment]
@bwang2453 There is currently no way to do this through the filter fields in the columns. This is something that we plan to support in the future but don't have a timeline for. Linking your question to the filtering epic #169 to keep track of it.

**Comment by Marc-Andre-Rivet** [comment]
Linked to epic, closing as there is no followup action for this issue/question.

The Plotly community forum (https://community.plot.ly/) is the best place to share your questions with the team and the larger community.
