### ISSUE TITLE
V2 per-column cell formatting

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#310]
This particular issue only pertains to the following capabilities. Of course, there are many additional cell formatting functionality that we can consider in the future or with an additional sponsor :)

1. Support for determining the number of visible decimal places
2. Support for prefixes and suffixes (e.g. `$` or `%`)
3. Support for displaying comma separators in numbers (e.g. 3,401,403 instead of 3401403)

The following constraints apply to value formatting:
- It is only applied on a per-column basis
- When editing the cells, the formatting features aren’t displayed. For example, if the cell displays “$3,401,403”, then when you edit this cell it will display “3401403”
- Regional formatting is not considered. For example, if you specify a column as “$” or comma-separated, it will not change format depending on the locale (i.e. it will not become “3.401.403” if viewed in a European country).

**Comment by chriddyp** [comment]
this is done now, right @Marc-Andre-Rivet ?

**Comment by Marc-Andre-Rivet** [comment]
Closed by https://github.com/plotly/dash-table/pull/377
