### ISSUE TITLE
Improved cell border formatting

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#311]
- Ability to change the color of the borders of any cell (left, right, top, or bottom)
- Borders can be removed, added, and the color can be changed
- “Double Border” will not be supported
- Border weight will not be configurable.

_Note that implementing variable border weights will be considerable more work as it will impact the size of cells, cell alignment, virtualization, and more. We can consider this feature in the future._
_Without modifying the weight of the borders, you will be able to mimic a hidden border to setting the border color to be the background color of the cell. A thicker border could be mimicked via a darker color._

**Comment by larissaleite** [comment]
Hi, thanks for this! Any idea when it should be released?

**Comment by chriddyp** [comment]
@larissaleite - this is currently in progress - expect a release within the next couple of weeks

**Comment by Marc-Andre-Rivet** [comment]
Fixed by https://github.com/plotly/dash-table/pull/424. Closing.
