### ISSUE TITLE
Ability to clear the contents of a column

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#315]
- The UI for this feature may overload the existing `x` button on the column or it may introduce a new icon or an additional context menu.
- Deleting the contents of a column will delete the contents across all pages (if pagination is enabled)
- If a filtering expression is applied on a column of which the contents are deleted, the filter will be cleared as well.

**Comment by Marc-Andre-Rivet** [comment]
Discussion notes: Add a `clearable` nested prop to `columns` that has the same type as `deletable` -- some "eraser" icon will represent it. It will behave just like delete but will not delete the columns.

**Comment by Marc-Andre-Rivet** [comment]
The current `column.deletable` action implementation prevents the `x` from being displayed if the pagination is custom (not controlled by the table), the current implementation of `column.clearable` will use the same limitation.

> If a filtering expression is applied on a column of which the contents are deleted, the filter will be cleared as well.

This is not being done for `column.deletable` right now. As this is implemented for `column.clearable`, it should behave the same for the other.
