### ISSUE TITLE
ability to conditionally format columns if editing is disabled [Sponsored: Due May 1]

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#320]
Enable Dash developers to update the style depending on whether the column is editable or not.
This would likely be an additional option in our `style_data_conditional` property (see e.g. https://dash.plot.ly/datatable/style)

**Comment by Marc-Andre-Rivet** [comment]
All `style_**_conditional` to get an additional `is_editable: boolean` nested prop inside the `if`.

For each, we need to modify the calculation pipeline to take the new condition into consideration.
Have a look at `dash-table/derived/style/index.ts` to see how it all glues together.

**Comment by alexcjohnson** [comment]
Closed by #462
