### ISSUE TITLE
[dash-table] Improve dropdown props typing

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-table#339]
dropdown_properties, column_static_dropdown, column_conditional_dropdowns are very loosely typed at the moment -- that typing can be improved, amongst other things by using PropTypes.objectOf which defined the structure of the object's properties but allows any property name.

This relates to #156, #143.

**Comment by alexcjohnson** [comment]
The new structure as of #446 is pretty complete in its typing.
