### ISSUE TITLE
Datatable 3.2.0 failing with: dash.dash.exceptions.NoLayoutException: Layout must be a dash component or a function that returns a dash component.

### ISSUE THREAD

**Issue by davidghill** [plotly/dash-table#357]
An upgrade broke datatables for my environment, and I haven't been able to undo the break even after rolling back the update, completely uninstalling python and starting from scratch, etc.  Any app with a datatable is failing with the following error:

```
Dash Version 0.35.2
Dash DataTable Version 3.2.0
Dash Core Components Version 0.43.0
Dash HTML Components Version 0.13.5
Pandas Version 0.24.0
Numpy Version 1.16.1
Plotly Version 3.5.0
cx_Oracle Version 12.2.0.1.0

Traceback

 (most recent call last):
  File "C:\Users\david\.spyder-py3\dataagg_Test_001.py", line 73, in <module>
    data=dataaggrun.to_dict("rows"),
  File "C:\Users\david\AppData\Roaming\Python\Python37\site-packages\dash\dash\dash.py", line 279, in layout
    ''
dash.dash.exceptions.NoLayoutException: Layout must be a dash component or a function that returns a dash component.
```

It appears to be looking for a layout component, but none is require for a datatable. I downgraded back to my original versions, but the issue persists.  My simplified code is below:

```
import dash
import dash_table
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd
import numpy as np
import plotly
import cx_Oracle

#... some stuff here

#Retrieve DATAAGGRUN records
dataaggrunhist where processname = \'DATA AGGREGATION\' and status = \'COMPLETE\') order by dataaggrunid desc'
dataaggrun_query = 'select * from dataaggrun where dataaggrunid =4 order by dataaggrunid desc'
dataaggrun = pd.read_sql(dataaggrun_query, con= db)

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div([
    html.Div(id='dataaggrun-table-container'),
 
    dash_table.DataTable(
        id='dataaggrun-table',
        columns=[
            {"name": i, "id": i} for i in dataaggrun.columns
        ],
        data=dataaggrun.to_dict("rows"),
    ),
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

The code from the dash.py file being referenced is below:

```
    @layout.setter
    def layout(self, value):
        if (not isinstance(value, Component) and
                not isinstance(value, collections.Callable)):
            raise exceptions.NoLayoutException(
                ''
                'Layout must be a dash component '
                'or a function that returns '
                'a dash component.')
```

**Comment by Marc-Andre-Rivet** [comment]
@davidghill The break still being present after rolling back seems indicative of another underlying problem. A few things before we start digging down further.

- Could you update dash to the latest version (0.36.0)
- Can you confirm the version of the dash-renderer? Latest is 0.17.0

Do you have this error when running one of the pre-baked examples from https://dash.plot.ly/datatable?

Say:
```
import dash
import dash_table
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

app = dash.Dash(__name__)

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict("rows"),
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by davidghill** [comment]
Thanks for the reply.  Now I'm having more issues. My pip isn't working due to missing ssl in python:

> pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

I've tried manually downloading the packages from https://pypi.org/simple/ssl/ and going back and downloading all of the required items that failed (setuptools, etc.)  I've uninstalled and reinstalled anaconda3 64 as well.

Now I'm getting this below. IS my python install buggy somehow?
```
C:\Users\david>pip install "C:\Users\david\Downloads\ssl-1.16 (3).tar.gz"
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Processing c:\users\david\downloads\ssl-1.16 (3).tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\david\AppData\Local\Temp\pip-req-build-nsvarl1z\setup.py", line 33
        print 'looking for', f
                          ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('looking for', f)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\david\AppData\Local\Temp\pip-req-build-nsvarl1z\

C:\Users\david>pip install "C:\Users\david\Downloads\ssl-1.15 (1).tar.gz"
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Processing c:\users\david\downloads\ssl-1.15 (1).tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\david\AppData\Local\Temp\pip-req-build-1v_40yg4\setup.py", line 74
        print 'looking for', f
                          ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('looking for', f)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\david\AppData\Local\Temp\pip-req-build-1v_40yg4\
```

**Comment by Marc-Andre-Rivet** [comment]
Feels like the script ran against python2 and then against python3 (enforcing parentheses)?

As this seems to be more of an environmental issue, I think you'll have better chances of finding a resolution to this issue by sharing it on the community forum (https://community.plot.ly/).

**Comment by anocella** [comment]
@davidghill I happen to be subscribed to this repo so I skimmed the email I got for this issue. You definitely shouldn't need to install the SSL package, and as @Marc-Andre-Rivet pointed out what you're trying to install is a Python2 package in a Python3 environment. Moreover, it is an *old* package. This is in the `setup.py`:

```
if (sys.version_info >= (2, 6, 0)):
    raise ValueError("This extension should not be used with "
                     + "Python 2.6 or later (already built in), "
                     + "and has not been tested with Python 2.3.4 "
                     + "or earlier.")
```

You may want to look at https://stackoverflow.com/questions/41328451/ssl-module-in-python-is-not-available-when-installing-package-with-pip3.

**Comment by davidghill** [comment]
Thanks everyone. I was able to get running again once I fixed my windows environmental variables with some additional paths. Thank you for the direction!

**Comment by davidghill** [comment]
> @davidghill The break still being present after rolling back seems indicative of another underlying problem. A few things before we start digging down further.
> 
> * Could you update dash to the latest version (0.36.0)
> * Can you confirm the version of the dash-renderer? Latest is 0.17.0
> 
> Do you have this error when running one of the pre-baked examples from https://dash.plot.ly/datatable?
> 
> Say:
> 
> ```
> import dash
> import dash_table
> import pandas as pd
> 
> df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')
> 
> app = dash.Dash(__name__)
> 
> app.layout = dash_table.DataTable(
>     id='table',
>     columns=[{"name": i, "id": i} for i in df.columns],
>     data=df.to_dict("rows"),
> )
> 
> if __name__ == '__main__':
>     app.run_server(debug=True)
> ```

Thanks. This works now with the environment variable additions. Much appreciated.
