### ISSUE TITLE
Allow numbers as column names

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#358]
I haven't reproduced this, but it looks like numbers might not be supported as column names:
https://community.plot.ly/t/numbers-in-column-headers/18881

**Comment by Marc-Andre-Rivet** [comment]
@chriddyp That's quite possible. I remember we discussed removing support for `number` column ids previously (as in actual `number` type). There are some cases where JS behaves bizarrely when given a number string or when given an actual number. We might be hitting one such case.

We've had a related issue previously with maps caching `0` as `"0"` and never caching for example..

**Comment by alexcjohnson** [comment]
As of v4.0 we're explicitly not allowing numbers as column IDs - they all need to be strings.
