### ISSUE TITLE
[WIP] Table v4 wishlist

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-table#360]
**Standardize props**
- conditional and static property (tooltips, dropdowns, styles) are expressed as arrays or keyed objects  depending on the assumptions and the conditional API at the time of implementation
- revisit the column id as number assumption -- originally the table supported both string and number keys for column ids but has moved towards strings only, this impacts the API breakdown in the point above

**Comment by alexcjohnson** [comment]
Closed by #446
