### ISSUE TITLE
Table triggers render on mouse move

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-table#379]
Since the tooltip feature addition, the table is re-rendering on each mouse move. While it's mostly cached an unexpensive vs. an actual full re-render, this still takes ~15ms and happens extremely often. 

- there's no need to re-render the table when moving inside a cell, a normal debounce for activating the tooltip will do
- there's no need to do this if the table doesn't have tooltips (or better yet, if the cells involved do not have tooltips)

**Comment by alexcjohnson** [comment]
@Marc-Andre-Rivet was this covered in your recent 🐎 PRs #463 and #466 ?

**Comment by Marc-Andre-Rivet** [comment]
Yes. This issue is resolved. Closing.
