### ISSUE TITLE
[Feature Request] Text link to html A in Cells

### ISSUE THREAD

**Issue by loretoparisi** [plotly/dash-table#393]
Is it possibile to transform text url in cells as html `<a/>` tags?

**Comment by Marc-Andre-Rivet** [comment]
@loretoparisi It's not currently possible but it has been discussed, is something we plan on implementing, but is not on the roadmap right now. Cross-linking with the data types epic #166 for reference.

**Comment by chriddyp** [comment]
Possible-enough with the new markdown support (which implicitly supports links)

**Comment by loretoparisi** [comment]
@chriddyp great! any docs available already?

**Comment by Marc-Andre-Rivet** [comment]
@loretoparisi There's a working example in the `Dash v1.8.0` [release announcement](https://community.plot.ly/t/dash-v1-8-0-release/33629) and some more info in the [table documentation](https://dash.plot.ly/datatable/typing).
