### ISSUE TITLE
filtering syntax documentation

### ISSUE THREAD

**Issue by letianzj** [plotly/dash-table#407]
Is there a documentation for data-table filtering. For example, how to filter rows containing (or not containing) a substring? Thanks.

So far I found from dash user guide are
-- Enter eq "Asia" in the "continent" column
-- Enter > num(5000) in the "gdpPercap" column
-- Enter < num(80) in the lifeExp column

**Comment by Marc-Andre-Rivet** [comment]
@letianzj Thanks for the question. The feature is being reworked in depth and part of that work will include better documentation for filtering. You can follow the progress in this [PR](https://github.com/plotly/dash-table/pull/397)

> how to filter rows containing (or not containing) a substring

There's currently no syntax for `contains` but it is something we want to add sooner than later.

**Comment by letianzj** [comment]
Thanks @Marc-Andre-Rivet Looking forward to more filtering functions and docs.
