### ISSUE TITLE
Pagination - move current_page out of pagination_settings?

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-table#411]
`current_page` is more state than configuration - it would be nice to be able to both create `pagination_settings` without involving `current_page`, and to subscribe to `current_page` in a callback independent of `pagination_settings`. I might also move `pagination_mode` to be `pagination_settings.mode` while we're at it...

**Comment by r-chris** [comment]
I believe the latest release (v4.0.0) removed the `pagination_settings` altogether to what is now `page_action`.  `current_page` is probably `page_current` - so I assume you can close this now?

**Comment by alexcjohnson** [comment]
Thanks @r-chris you're right - closed by https://github.com/plotly/dash-table/pull/446
