### ISSUE TITLE
Dash - Display table according to dropdown

### ISSUE THREAD

**Issue by divy10** [plotly/dash-table#452]
Hi! 
This is my first post here! :)

I have been trying to implement a callback for two different drop downs that will generate a table corresponding to the option chosen. 

As an example:
dcc.Dropdown(
                                id = 'country',
                                options=[
                                    {'label': 'No filter', 'value': 0},
                                    {'label': 'USA', 'value': 1},
                                    {'label': 'UK', 'value': 2},
                                    {'label': 'Canada', 'value': 3},
                                    {'label': 'Mexico', 'value': 4}])
dcc.Dropdown(
                                id = 'products',
                                options=[
                                    {'label': 'No filter', 'value': 0},
                                    {'label': 'Detergents', 'value': 1},
                                    {'label': 'Soaps', 'value': 2},
                                    {'label': 'Toothpaste', 'value': 3},
                                    {'label': 'Creams', 'value': 4}])

Say, if I choose UK and Soaps from the dropdown, I want the dash to display a table which shows the brands of soaps available in UK and their prices or any other value corresponding to these two inputs.

Any solutions on how to implement this?

Help would be really appreciated.
Thank you.

**Comment by alexcjohnson** [comment]
Hi @divy10 - welcome! This kind of question is best suited to https://community.plot.ly/c/dash (we prefer to reserve github for bug reports and feature requests) but to get you started: assuming you understand how to make a table that shows some (fixed) data, the next step is to put that table into the layout with no data, then connect its `data` prop to the dropdowns via a callback:
```py
@app.callback(
    Output('my-table', 'data'),
    [Input('country', 'value'), Input('products', 'value')]
)
def make_data(country, product):
    # query that returns rows of data objects for this country and product
```
