### ISSUE TITLE
Dash Table misrepresents numbers from pandas dataframe

### ISSUE THREAD

**Issue by weiyiyin0321** [plotly/dash-table#481]
Dash Table is changing the values of my numbers from my pandas dataframe. Here is a working example.

```
import dash_table
import dash_html_components as html
import dash
import pandas as pd

df = pd.DataFrame({
    'col1': [1108034252451565568, 1108034253040459776]
})

app = dash.Dash()

app.layout = html.Div(children=[
    dash_table.DataTable(data=df.to_dict('r'), columns=[
                         {'name': i, 'id': i} for i in df.columns])
])

if __name__ == '__main__':
    app.run_server(debug=True, port=9000)
```

Here's what I see on the webpage:

![Screenshot_2019-06-25 Dash](https://user-images.githubusercontent.com/33683156/60119916-de01c280-973c-11e9-96cc-73baccde9480.png)

It looks like it's rounding up to the nearest hundred? When I convert the type to a string, the values are displayed properly. I'm currently on the latest dash and dash-table from pip.

**Comment by alexcjohnson** [comment]
I'm afraid you've reached the limits of Javascript's numeric precision. Javascript treats all numbers as double precision floats.

In the Chrome console:
<img width="165" alt="Screen Shot 2019-06-25 at 2 55 53 PM" src="https://user-images.githubusercontent.com/2678795/60125592-21b6f500-975a-11e9-8395-b2af44851e15.png">

So yeah, other than using strings I'm not sure what we can do.

**Comment by weiyiyin0321** [comment]
I see. I guess for display purposes it's not a big deal as long as I'm not trying to sort. Thank you!
