### ISSUE TITLE
Hidden columns persistence

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-table#509]
Follow up to the `hidden columns` feature work in https://github.com/plotly/dash-table/issues/314. Props associated with table based persistence are to be tagged as `beta`.

`persisted`: PropTypes.arrayOf(PropTypes.oneOf(['hidden_columns'))

During initialization, the stored value is used if `hidden_columns=None`. The stored value will be assigned to `hidden_columns` and will trigger a `setProps`.

**Comment by alexcjohnson** [comment]
Closed by #566
