### ISSUE TITLE
Add a HTML component into a cell

### ISSUE THREAD

**Issue by lucasvannoort** [plotly/dash-table#514]
Hello guys,

I have to add custom html element into datatable cells like :

html.Button(["Change choice"], className="btn btn-primary btn-round")
or
html.Span(["37%"], className="btn btn-primary btn-outline-primary btn-round score")

How can I make that please ?

**Comment by Marc-Andre-Rivet** [comment]
@lucasvannoort Thanks for the question. This is not currently possible in the table as it would either require supporting components as properties, which we do not do at the moment and is still on an unknown timeline, or requiring extra representation options in the table, which is not in the plans in the short term.

**Comment by Marc-Andre-Rivet** [comment]
Support for markdown syntax was added to the table in [Dash v1.8.0](https://community.plot.ly/t/dash-v1-8-0-release/33629) and should support most html use-cases inside the table.
