### ISSUE TITLE
Virtualized table error when navigating past the lower edge of the viewport

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-table#520]
Issue first described in https://github.com/plotly/dash-table/issues/447.

The bug seems fixed in `dash==1.0.2` but that can only have happened by random luck.

There's no actual fix to be done here, just adding a test to make sure navigating with the keyboard past the edge of the viewport (top or bottom) does not trigger a console error / behaves correctly.

**Comment by shammamah** [comment]
@Marc-Andre-Rivet 

>There's no actual fix to be done here, just adding a test to make sure navigating with the keyboard past the edge of the viewport (top or bottom) does not trigger a console error / behaves correctly.

In the original issue you linked, it appears as though the user has to do the following to replicate the error: 
1. Select a cell with the mouse 
2. Scroll down 
3. Select another cell that was initially outside of the viewport 

Should this still go in the keyboard tests?

**Comment by shammamah** [comment]
I'm thinking this might also have something to do with a related test: 

https://github.com/plotly/dash-table/blob/ea3a78b0613e4bc3131719ef6eac8b150f34e7ed/tests/cypress/src/DashTable.ts#L26
