### ISSUE TITLE
Copy/paste does not work in certain situations

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-table#526]
Clicking in cell in first column with the standalone demo code (npm run build.watch + localhost:8080) does not trigger a `copy`. Clicking on cell in the 2nd column triggers a `copy`. Navigating with mouse to first column from 2nd column cell, `copy` can now be triggered exactly once.

There is a global `onCopy` handler in the controlled table. Seems like in certain situations the cell's input element may be capturing that event instead.

This may be a regression. Unsure how long this has been a problem.

**Comment by michaelbabyn** [comment]
This came up in a support ticket and I was able to reproduce in `dash-table > 3.6.0`. If I select a chunk of the table and then try to copy it into excel it doesn't work unless I first click on another cell in the same selection before I press ctl-c. 

I tested this on ubuntu 18.04 using chrome and firefox
