### ISSUE TITLE
Tooltip Not Working on Dash/Datatable update 

### ISSUE THREAD

**Issue by Motta23** [plotly/dash-table#541]
Following the Dash Experiment (https://community.plot.ly/t/dash-datatable-tooltips/6327/3) the tooltip works on Dash version 0.39 (Datatable version 3.6.0), but not on 1.0.0+ (Datatable version 4.1.0). 

I know that the naming of 'tooltips' has been changed in version 1.0.0 (although it's not very clear whether it should be 'tooltip' or 'tooltip_data'), but both of these don't seem to work:

```
import dash
import dash_core_components as dcc
import dash_html_components as html
import dash_table as table

import pandas as pd
import textwrap

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv')

print(dash.__version__)
print(table.__version__)

app = dash.Dash(__name__)
app.scripts.config.serve_locally = True
app.css.config.serve_locally = True

def create_tooltip(cell):
    try:
        num = float(cell)
        return textwrap.dedent(
            '''
            Tooltip for value **{value:+.2f}**.
            | Multiplier | Value |  Percent |
            |-------|-------|---------------|
            | 1     | {value_1:+.2f}     | {value_1:+.2f}% |
            | 2     | {value_2:+.2f}     | {value_2:+.2f}% |
            | 3     | {value_3:+.2f}     | {value_3:+.2f}% |
            '''.format(
                value=num,
                value_1=num,
                value_2=num * 2,
                value_3=num * 3
            )
        )
    except:
        return textwrap.dedent(
            '''
            Tooltip: **{value}**.
            '''.format(value=cell)
        )


app.layout = html.Div([
    table.DataTable(
        columns = [{'name': i, 'id': i} for i in df.columns],
        data=df.to_dict('rows'),
        tooltip={
            col: [
                {
                    'type': 'markdown',
                    'value': create_tooltip(df.loc[i, col])
                }
                for i in range(len(df))
            ]
            for col in df.columns
        }
    )
])

if __name__ == '__main__':
    app.run_server(debug=True)
```

I've tested the code above (with the term 'tooltips' instead of 'tooltip') on Dash 0.39 (Datatable version 3.6.0) and it works fine. It doesn't however on the new version. Reading through the docs, the only change has been on the term 'tooltips'. Unless I'm doing something horribly wrong, I think this is a bug.

**Comment by Jendoliver** [comment]
I think the actual property you might be looking for is now `tooltip_data` instead, although I'm not really sure of how it should be constructed right now. For me this is more a lack of documentation than a bug, since I couldn't find any example with the new syntax...

![image](https://user-images.githubusercontent.com/23485344/62858606-0c425e00-bcfb-11e9-92c7-cf5a5632a471.png)

Did you figure this out? I'm trying to get some tooltips working on my own table as well 😄

**Comment by Motta23** [comment]
Unfortunately not. I'm not sure whether this is a documentation issue or a bug, as the documentation explicitly mentions that only the word 'tooltips' is changed and nothing else. 

If it's a documentation issue, please update that with the changes that are made. That would then clear it up for a lot of people (also on the Plotly Community page). And if it's a bug, please put it in the backlog.

Awesome package btw, loving it :)

**Comment by Motta23** [comment]
Apparently it's the way the tooltip is called is a bit different than in the earlier versions, so no bug here. For future reference: On the community plotly website Titi31 gave the right syntax:

```
Hi! According to the documentation, you can make it work like this :

tooltip_data=[{‘my_column_name’: ‘this is a test tooltip’ }]

Please note however that it will work only for the first row, you need to iterate if you want specific value on the rest of the column.

Otherwise, you can use the tooltip argument:

tooltip={‘my_column_name’: ‘this is a test tooltip’ }
```

Link: https://community.plot.ly/t/dash-datatable-tooltips/6327/8

**Comment by Jendoliver** [comment]
Thank you for sharing it!!

**Comment by happyshows** [comment]
@Motta23 I still couldn't get it working, could you share a reproducible example?

**Comment by JeroneGagliano** [comment]
I am able to get the tooltip to work but only on the rows of data. I would
like the tooltip to show up as a hover over the header name of the column
in the table. This would be useful to explain to user what that header
means or how the data in that column were calculated or assumptions made,
etc.

**Comment by happyshows** [comment]
I have tried numerous combinations (due to lack of updated documentation).

```
tooltip={
                col: col
                for col in _df.columns}
```
will produce column wise tooltip, whenever I tried to customize cell wise tooltip via additional level of loop, the data table does not respond :(

**Comment by happyshows** [comment]
k finally I got it, you need to wrap the row loop outside of the column id loop (not inside)

```
tooltip_data=[{
                col: f"{col} {i} th row"
                for col in _df.columns} for i in range(0,_df.shape[0])],
```

**Comment by vlemmy** [comment]
I spent hours trying to get the right structure to pass to `tooltip_data` but it didn't like anything. with it grouped at first nesting by row, and then by columns, and without a specified 'value' key, assuming it was taken as expected and so on. this is the last i tried ---- has anyone got any advice?

`[{col: {'value': df.loc[i,col]} for col in df.columns} for i in range(len(df))]

**Comment by ybressler** [comment]
@vlemmy  I'm having similar issues....
