### ISSUE TITLE
v1.1.0 datatable hidden_columns/exporting loses hidden headers when export_header='names'

### ISSUE THREAD

**Issue by laoxu0212** [plotly/dash-table#546]
Hi there,

hidden_columns in 1.1.0 has really helped me a lot, however, here comes the question with exporting:

After using hidden_columns to hide some of the columns, I need to export data(no matter what is displayed after hiding several columns or the whole table).

It seems that the **data** of hidden columns will be exported anyway but the **headers** of them will not if I set **export_headers='names'.** It just leaves several data without headers.

I think the "ids" or the "names" should be same for the headers but the content, therefore, could I believe that there might be something wrong?

Here is a demo code to show that problem:

`import dash
import dash_table

app = dash.Dash(__name__)

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i} for i in ['a', 'b', 'c', 'd']],
    data=[{'a':1, 'b':1, 'c':1, 'd':1}, {'a':1, 'b':1, 'c':1, 'd':1},{'a':1, 'b':1, 'c':1, 'd':1},{'a':1, 'b':1, 'c':1, 'd':1}],
    hidden_columns=['d'],
    export_format='csv',
    export_headers='names'
)

if __name__ == '__main__':
    app.run_server(debug=True)`

And the csv looks like:
![image](https://user-images.githubusercontent.com/20391173/63058392-71d04f00-bea1-11e9-9c10-7f791e58a39e.png)

**Comment by Marc-Andre-Rivet** [comment]
Fixing the default behavior to use visible columns for both data / headers.

A new prop `export_columns` will be added to allow exporting all the columns if desired. Value can be `all` or `visible`.

**Comment by laoxu0212** [comment]
Thanks for your enhancement on #592  
I think I might not have clarified the bug:

Currently all the columns will be exported. 
If you choose export_headers='names' , only visible columns' headers will be shown.
This leaves some columns in CSV without headers.

If you choose export_headers='ids', all columns' headers will be shown.

"export_columns" mentioned in https://github.com/plotly/dash-table/pull/592#issuecomment-533290011 is a great enhancement. But I'm afraid that if we don't set this property, we may still see some data columns without headers.

Here we got:
    columns=[{"name": 'column-' + i, "id": 'column-' + i} for i in ['a', 'b', 'c', 'd']],
    data=[{'column-a': 'a', 'column-b': 'b', 'column-c': 'c', 'column-d': 'd'}] * 3,
    hidden_columns=['column-c'],
    export_format='csv',
    **export_headers='names'**

![image](https://user-images.githubusercontent.com/20391173/65345086-48849c00-db8e-11e9-8ade-8b9c8d9c7028.png)

But here we got:
    columns=[{"name": 'column-' + i, "id": 'column-' + i} for i in ['a', 'b', 'c', 'd']],
    data=[{'column-a': 'a', 'column-b': 'b', 'column-c': 'c', 'column-d': 'd'}] * 3,
    hidden_columns=['column-c'],
    export_format='csv',
    **export_headers='ids'**

![image](https://user-images.githubusercontent.com/20391173/65345274-b9c44f00-db8e-11e9-9a9a-7958352785b2.png)

At least I believe leaving columns without hears in exported file is not correct.

**Comment by Marc-Andre-Rivet** [comment]
@laoxu0212 The changes in #592 should cover your current use case and be available in the `v1.4.0` release. With the fix, the columns and headers will match as expected, whether there are hidden columns or not, and whether you want to export all of them or not.

The additional prop is an addition to decide if you want to have all the columns or only the visible ones on export as both scenarios seem valid.
