### ISSUE TITLE
Provide documentation for column

### ISSUE THREAD

**Issue by orenbenkiki** [plotly/dash-table#551]
The documentation in https://dash.plot.ly/datatable/reference says "Columns describes various aspects about each individual column." but there is no list of supported keys and their semantics (other than mentioning that `name` and `id` are required).

**Comment by alexcjohnson** [comment]
In progress, just waiting for some changes in the upcoming 1.2 release https://github.com/plotly/dash-docs/pull/479#issuecomment-518020180
