### ISSUE TITLE
Export option - data columns are in a different order to the header names

### ISSUE THREAD

**Issue by theoplatt** [plotly/dash-table#553]
This is connected to an issue noted in the community forum - 

https://community.plot.ly/t/datatable-export-columns-not-in-the-same-order-as-the-header/27507

When using the export functionality the header comes out in the correct order and matches the displayed table but the columns of data are in a different order. The net result is that the header names do not match the content.

This can be seen by using the export button on https://dash.plot.ly/datatable/editable and examining the results.

**Comment by alexcjohnson** [comment]
Confirmed, thanks for the report @theoplatt - we'll get it taken care of.

**Comment by Marc-Andre-Rivet** [comment]
Closed by https://github.com/plotly/dash-table/pull/592
