### ISSUE TITLE
Cypress server copy/paste test failing on certain machines

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-table#577]
See, e.g., https://circleci.com/gh/plotly/dash-table/12387 from #484 
cc @Marc-Andre-Rivet 

In the failing test "copy paste BE roundtrip on copy-paste on cell modification", the cell at (0, 0) has an initial value of "0". It is subsequently clicked on and edited by typing the value "10" into the input. The test then checks whether or not the value of the cell is "10". 
The test fails due to the value not updating. On the CI machine, it is because the cell's value remains "0"; on my machine the value is "00". 

This test can be resolved by adding in a `cy.wait(0)` between clicking on the cell and entering the value "10" (see https://github.com/plotly/dash-table/pull/484/commits/5fc1cd5f7047563cbc1c44c0d1540c3770634dc0), but it would be a good idea to look into why exactly this is happening.

**Comment by Marc-Andre-Rivet** [comment]
This is moot. Fixed by https://github.com/plotly/dash-table/pull/581 and https://github.com/plotly/dash-table/pull/484
