### ISSUE TITLE
[BUG] active_cell docstring is wrong - No key 'row_id' for active_cell in dash_table.DataTable

### ISSUE THREAD

**Issue by Aryalexa** [plotly/dash-table#651]
Hello.
I'm working with `dash_table.DataTable` and reading the docs I found `row_id` in the `active_cell `argument. Examples on the Dash web are using it (https://dash.plot.ly/datatable/interactivity).

``` 
- active_cell (dict; optional): The row and column indices and IDs of the currently active cell. 
active_cell has the following type: dict containing keys 'row', 'column', 'row_id', 'column_id'.
Those keys have the following types:
  - row (number; optional)
  - column (number; optional)
  - row_id (string | number; optional)
  - column_id (string; optional)
```

**Context**

-  dash libraries
```
dash                               1.4.1
dash-core-components               1.3.1
dash-daq                           0.2.1
dash-html-components               1.0.1
dash-renderer                      1.1.2
dash-table                         4.4.1

```

**The bug**

It seems `active_cell['row_id']` is not supported.
This is what I get exploring the `active_cell` dictionary

```
', '.join(['{}:{}'.format(k, v) for k, v in active_cell.items()])
# result: row:5, column:4, column_id:Company
```
I also have a screenshot where I force the code to get the value and get an error.

![image](https://user-images.githubusercontent.com/12053430/69435118-429e6900-0d3f-11ea-94d6-a23ba514f813.png)

**Comment by arrubyyan** [comment]
one way I found to go around it is using:
virtual_row_ids[active_cell['row']]

is there any better way? cause the 'row' keeps changing during the transformation

**Comment by Rothenhouser** [comment]
I think this may just be a problem with slightly unclear documentation. In case anyone else lands here after googling this: If you want to use the `row_id` of the active cell, the `data` property in your data table *must* have an `'id'` key for each row. That worked for me.

This is made clear in the section on row IDs and the example here: https://dash.plot.ly/datatable/interactivity.
