### ISSUE TITLE
When selecting a dropdown, I get shot to the bottom of my very long table

### ISSUE THREAD

**Issue by rbrasga** [plotly/dash-table#653]
I created a dash_table with 100 rows, where in 1 column each cell has a simple dropdown

If I click the dropdown at the top - it sends me to the bottom of the page - out of view of that drop down (making that dropdown inaccessible).

Let me know if this is a user-error. Although I searched for any related issues to dropdowns and none matched my case.

I've been using dash_table just fine without issues, until I tried adding dropdowns to a single column with many rows.

**Comment by rbrasga** [comment]
*It might be worth noting that setting style_cell to position: relative resolves the issue of getting shot to the bottom of the page, but then I can't view the dropdown.

**Comment by rbrasga** [comment]
And... I "fixed" it with `page_size = 5`

**Comment by radziej** [comment]
I think the same issue is being discussed in #486. There does not seem to be a solution or workaround (that does not rely on pagination) at the moment.

**Comment by rbrasga** [comment]
Thank you for the reference. Closed as duplicate of #486 .

I will look into a work-around (that does not rely on pagination) since it appears to be a valid issue.
