### ISSUE TITLE
How to put an image in a table cell?

### ISSUE THREAD

**Issue by ValeryPolyakov** [plotly/dash-table#673]
I would like to put an image(s) in a table cell(s). The image could be an embedded svg or refer to a .png file location. For some reason the table does not interpret the <img..../> tag. 

If it is not possible directly, maybe you have some workarounds.

Thanks for your help.

**Comment by Marc-Andre-Rivet** [comment]
Dash v1.8.0 added support for markdowns in the table. There's an example in the [release announcement](https://community.plot.ly/t/dash-v1-8-0-release/33629/5).

**Comment by Nishan-Pradhan** [comment]
Is it possible to put an image in this same way into a basic plotly `go.Table` cell? Thanks

**Comment by alexcjohnson** [comment]
No, `go.Table` (from plotly.py) has a very different interface and does not support images in any way AFAIK. You can use a very limited subset of HTML in cell contents (`<a>`, `<b>`, `<em>`, `<i>`, `<br>`, `<span>`, `<sub>`, `<sup>`, with `style` attributes and `href` for `<a>`) but that's it.

**Comment by stazam** [comment]
Anything has changed? Is it possible now in basic plotly tables?
