### ISSUE TITLE
DataTable: Copying selected cells to clipboard requires an extra click on active cell

### ISSUE THREAD

**Issue by jko14** [plotly/dash-table#676]
Hi Dash Community!

I've noticed when using DataTables online, it is now possible to copy information from multiple selected cells to the clipboard; however, it requires users select all cells and _then_ click once more on the initial "active cell" before the information is copied. Is this an easy issue to resolve?

**Comment by emiliobasualdo** [comment]
I believe this error still persists.
I can reproduce it on 
dash==1.20.0
dash-bootstrap-components==0.12.2
dash-core-components==1.16.0
dash-html-components==1.1.3
dash-renderer==1.9.1
dash-table==4.11.3
Flask==2.0.1
