### ISSUE TITLE
selecting a dropdown alters row height

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-table#69]
undesired behavior: selecting a dropdown increases the row height

**Comment by Marc-Andre-Rivet** [comment]
@cldougl Table has changed a lot since September -- mind having another look and confirming if the issue still exists? I've made a few attempts but it looks like it's behaving fine.

**Comment by Marc-Andre-Rivet** [comment]
Had another go at it. Unable to reproduce the issue. Closing. Please re-open if you can reproduce.
