### ISSUE TITLE
Docs - Override data cell styling on a cell by cell basis

### ISSUE THREAD

**Issue by schaefer01** [plotly/dash-table#697]
HI, 
I've read around and it (Override data cell styling on a cell by cell basis) appears to have been requested in one form or another since 2017, see 
https://community.plot.ly/t/dash-datatable-how-to-the-set-background-color-for-individual-cell/6277

Basically, my need is: Each cell has a good/bad value, and I'd like to assign a red/green background color to allow a user to quickly see bad values are present.

I already recoded my app from html tables to dash tables, and I'd hate have to go backwards, only to find you are working on the problem, and if I wait, you'll have solved it.
thanks,
  bob s

**Comment by chriddyp** [comment]
Fixed in https://github.com/plotly/dash-docs/pull/854/

See examples in https://dash.plotly.com/datatable/conditional-formatting
