### ISSUE TITLE
index column edit/delete button unusable

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-table#72]
we should consider removing the edit/delete buttons (remove altogether or make unactive) as it's not possible to remove this column:

![index](https://user-images.githubusercontent.com/2789078/45363932-cf2f9200-b5a6-11e8-99ae-b955b03ab860.gif)

**Comment by Marc-Andre-Rivet** [comment]
Column actions visibility is now fully driven by the props. If a column action is not available, the action button is not there. Closing as fixed.
