### ISSUE TITLE
Tooltip doesn't work with horizontal scroll

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#736]
As reported here: https://community.plotly.com/t/datatable-tooltip-view-appears-limited-to-scope-of-page-only/37576

**Comment by chriddyp** [comment]
cc @Marc-Andre-Rivet  - For when you are in the neighborhood

**Comment by tashrifbillah** [comment]
Thanks @chriddyp , happy to collaborate :)

**Comment by chriddyp** [comment]
@tashrifbillah - Could you share with version of dash-table you are using? If you are not on the latest, could you try upgrading and see if the issue persists?

**Comment by tashrifbillah** [comment]
Is it not the latest?
```python
In [9]: dash_table.__version__
Out[9]: '4.6.1
```

**Comment by chriddyp** [comment]
It's pretty close - The latest is `4.6.2`. You can upgrade with `pip install dash --upgrade`, however I suspect the issue will persist as we did not fix any issues related to this in 4.6.2 (https://github.com/plotly/dash-table/blob/dev/CHANGELOG.md).

**Comment by tashrifbillah** [comment]
Hi @chriddyp , I have an update for you. It appears that tooltip displays as expected on Internet Explorer 11. Previously, I was looking at Google Chrome only. Can you check this behavior at your end?

**Comment by cldougl** [comment]
This is still occurring in the latest version of[ Dash 1.14.0](https://github.com/plotly/dash/blob/dev/CHANGELOG.md#1140---2020-07-27) (/ Dash Table)

**Comment by tashrifbillah** [comment]
Yeah, probably they didn't get time to work on it.

**Comment by dshenderson** [comment]
Is there any progress on this issue?  This bug is stopping us putting our app into production.

**Comment by chriddyp** [comment]
@dshenderson - This is the next item in the queue for us, so it should be available within a couple of weeks. For now, you'll need to downgrade `dash` if you need this feature and not the others.

**Comment by dshenderson** [comment]
Downgrading is not an option, as you fixed a critical bug in 1.14.0. Thanks.

**Comment by Marc-Andre-Rivet** [comment]
For the case described above the culprit seems to be a bad default style defined here: https://github.com/plotly/dash-table/blame/dev/src/dash-table/components/ControlledTable/index.tsx#L45
```
const DEFAULT_STYLE = { 
    width: '100%'
};
```

Changing it to:
```
const DEFAULT_STYLE = {
    width: '100%',
    overflow: 'auto'
};
```
or adding the following prop to the table:
```
style_table=dict(overflow='auto')
```
make the example table's tooltip behave as expected.

Not sure at this point what the implications of adding the CSS prop/value to the default is on all scenarios.Also, the container size is also off and causing different alignment issues between tooltip/cell for `fixed_columns=dict(headers=True)`

**Comment by tashrifbillah** [comment]
@Marc-Andre-Rivet , unfortunately, the issue doesn't appear fixed yet. Did you use the big csv file I provided?

I updated my dash installation which currently is:

```python
In [1]: import dash

In [2]: dash.__version__
Out[2]: '1.16.2'
```

I tried this on two browsers--Chrome and Edge on a Windows 10 computer. Happy to work on it again.

So where did you test it?

**Comment by chriddyp** [comment]
Thanks for following up @tashrifbillah ! Indeed it looks like the issue isn't fixed for your dataset. Reopening.

![tooltip](https://user-images.githubusercontent.com/1280389/94844861-b71c4c80-03d3-11eb-8565-44c2f9efb35a.gif)

> So where did you test it?

You can see the tests cases in the original PR: https://github.com/plotly/dash-table/pull/817/files

**Comment by Marc-Andre-Rivet** [comment]
Reproducing the issue for the unfixed rows+columns case, which is the only one that seems to be exhibiting the behavior and also the only one not currently covered by https://github.com/plotly/dash-table/pull/817/files#diff-1354323b0f137fce6c41eb5b41b46c6aR55. Adding it fails for all combinations. Investigating.

**Comment by tashrifbillah** [comment]
Hi @Marc-Andre-Rivet , if I do

> pip install git+https://github.com/plotly/dash-table.git@b61c8ccdb9c564a6665a92459fa3825314b4618e

I should be getting the latest commit, shouldn't I? If that is right, the issue still does not appear fixed for the csv file I provided.

**Comment by Marc-Andre-Rivet** [comment]
@tashrifbillah `dev` commits do not include a table build so I'm not sure what you would be running after running the command above.

If you want to run the latest from `dev` you will have to build it first and then install it. Something like this:
```
git clone --depth 1 https://github.com/plotly/dash-table.git
cd dash-table && npm ci && npm run build
pip install -e .
```

**Comment by tashrifbillah** [comment]
Tried but I ended up breaking my whole dash. I think I shall wait until 1.16.4 is available and then test. :)
