### ISSUE TITLE
pagination UI doesn't have 100% width

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#739]
Content that is displayed beneath the table can get rendered _next to_ the pagination UI instead of _below_ the pagination UI.

I believe that if the pagination UI had a 100% width and float right, this issue would be fixed.

![image](https://user-images.githubusercontent.com/1280389/79157469-77ac6600-7d89-11ea-8c76-f80b35259f9b.png)

**Comment by alexcjohnson** [comment]
Perhaps the same issue but a more severe form of it - a graph below the table will cover up pagination entirely. Here I reduced the opacity of the one of the graphs in https://dash.plotly.com/datatable/interactivity so you can see that the pagination section does exist, it's just completely covered:
<img width="784" alt="Screen Shot 2021-02-03 at 4 51 32 PM" src="https://user-images.githubusercontent.com/2678795/106814444-64cc9000-6640-11eb-8b36-543f78555de8.png">
