### ISSUE TITLE
With fixed rows, columns are as wide as the data and not the headers

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#740]
If the column headers are wider than the data (which is often the case with numerical tables & text column headers), then the width of the columns is too narrow and the column headers are cut off.

Without fixed columns, the column width expands to account for the width of the headers. I would expect the behavior to be the same with fixed headers.

Expected behavior:
![image](https://user-images.githubusercontent.com/1280389/79165955-0bd1f980-7d99-11ea-8a36-8d959b6eead2.png)

Default behavior with `fixed_rows`
![image](https://user-images.githubusercontent.com/1280389/79165971-168c8e80-7d99-11ea-9492-94ea7e3804ea.png)

Still undesirable behavior with header overflow:
![image](https://user-images.githubusercontent.com/1280389/79166008-286e3180-7d99-11ea-8474-ad5f1eb078c5.png)

**Comment by chriddyp** [comment]
(I thought that I had already raised this issue before, but I couldn't find it! Feel free to close if it's a duplicate)

**Comment by tashrifbillah** [comment]
I guess this is the one you refer to?
https://github.com/plotly/dash-table/issues/730

**Comment by chriddyp** [comment]
@tashrifbillah - SImilar, but not quite the same. This issue happens with or without column icons. The solution may end up fixing both issues though.

**Comment by chriddyp** [comment]
In this example, it looks like it's not actually an issue: the headers are wider than the cells but nothing is cut-off. 
![Screen Shot 2020-04-13 at 3 41 10 PM](https://user-images.githubusercontent.com/1280389/79167859-4f2e6700-7d9d-11ea-9044-989b66992054.png)

However, if I add more columns then the last column does not expand to it's width. It appears that `Column 10` is as wide as the other columns:
![Screen Shot 2020-04-13 at 3 43 27 PM](https://user-images.githubusercontent.com/1280389/79167958-90bf1200-7d9d-11ea-9228-50c052c0fc98.png)

**Comment by chriddyp** [comment]
Then, if I create 20 columns, we see the issue:
![image](https://user-images.githubusercontent.com/1280389/79168033-c237dd80-7d9d-11ea-8bcd-88bf276554fe.png)

**Comment by chriddyp** [comment]
> I thought that I had already raised this issue before

Ah found it - https://github.com/plotly/dash-table/issues/432
