### ISSUE TITLE
[BUG] DashTable and Wildcard / Pattern Matching callbacks not working

### ISSUE THREAD

**Issue by christianwengert** [plotly/dash-table#765]
**Describe your context**

I want to use a datatables 'data' attribute (or any other) in a callback but using the new pattern matching callbacks. 

This results in a seemingly unrelated JS error (parsing problem?)

```
Failed to execute 'addRule' on 'CSSStyleSheet': Failed to parse the rule '#{"action":"test","table":1} .dash-fixed-column tr { height: 30px; }'.
```

-  replace the result of `pip list | grep dash` below
```
dash                      1.11.0      
dash-bootstrap-components 0.9.2       
dash-canvas               0.1.0       
dash-core-components      1.9.1       
dash-cytoscape            0.1.1       
dash-daq                  0.3.3       
dash-extra-components     0.0.1       
dash-html-components      1.0.3       
dash-leaflet              0.0.3       
dash-planner              0.0.1       
dash-renderer             1.4.0       
dash-table                4.6.2    
```
-  if frontend related, tell us your Browser, Version and OS

    - OS: OSX
    - Browser Any

**Describe the bug**

Here is a test setup to reproduce the bug:

```
import dash
import dash_table
import pandas as pd
import dash_html_components as html
from dash.dependencies import MATCH, Output, Input, ALL

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

app = dash.Dash(__name__)

app.layout = html.Div([
    html.Div(id={'table': 1, 'action': 'output'}),
    dash_table.DataTable(
    id={'table': 1, 'action': 'test'},
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict('records'),
)])

@app.callback(Output({'table': MATCH, 'action': 'output'}, 'children'),
              [Input({'table': MATCH, 'action': 'test'}, 'active_cell')])
def test(xy):
    return xy

if __name__ == '__main__':
    app.run_server(debug=True)

```

**Expected behavior**

- No Failed to execute 'addRule' on 'CSSStyleSheet' Error
- Working callback

**Screenshots**

![image](https://user-images.githubusercontent.com/12936057/79241125-eaddd700-7e72-11ea-8b04-e6c6bc9f88cd.png)

![image](https://user-images.githubusercontent.com/12936057/79241157-f5986c00-7e72-11ea-8451-20682653b368.png)

**Comment by nehapuri31** [comment]
Hello,

I still face this issue even after upgrading to recent dash version. Has this been solved?

**Comment by manjeet87** [comment]
I am also facing the same issue, with latest Dash version. Object type ID is not going with even React components ehich require 'id' as 'string type'

**Comment by alexcjohnson** [comment]
@manjeet87 @nehapuri31 I'm not able to reproduce this today. Are you sure the latest dash (and dash_table) version is actually running in your script? Sometimes for example pip and conda give you a mismatch. You can check what's really running by adding `print(dash_table.__version__)` to your script immediately after the imports.

**Comment by ken19960315** [comment]
Hi @alexcjohnson ,
I still face the same issue with the latest version
![image](https://user-images.githubusercontent.com/22884270/119633092-f7897880-be43-11eb-8804-e6910eb8d111.png)
- Code:
```Python
dash_table.DataTable(
    id={'table':'interactive_table', 'index':'elapsed_%d'%tb},
    columns=[{'name':'Rank', 'id':'rank'},
             {'name':'Template ID', 'id':'template_id'},
             {'name':'Seconds', 'id':'seconds'}],
    data=[{'rank': i+1,
           'template_id': sub_df.template_id[i],
           'seconds': sub_df.time[i]} for i in range(10)]
)
```
- Error:
![image](https://user-images.githubusercontent.com/22884270/119633591-77174780-be44-11eb-9770-e8576d513b42.png)
