### ISSUE TITLE
Takes several seconds for fixed headers to resize to column widths after mouse up

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#776]
Discovered while investigating https://github.com/plotly/dash-table/issues/775

The columns aren't aligned when resizing the window. That's fine, however it takes about 5-10 seconds for them to resize appropriately after mouse-up

![resize](https://user-images.githubusercontent.com/1280389/81458517-9ff07000-914f-11ea-8306-9164815ca667.gif)

**Comment by chriddyp** [comment]
Fixed in https://github.com/plotly/dash-table/pull/793
![table-fixed-headers](https://user-images.githubusercontent.com/1280389/84958557-76155c00-b0b2-11ea-8681-5a9a5090a80e.gif)

**Comment by KlemenVrhovec** [comment]
I came across this issue in version 1.19.0. Did the issue reappear?
