### ISSUE TITLE
Headers aren't aligned with columns with fixed_rows

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#777]
Related to https://github.com/plotly/dash-table/issues/775 and https://github.com/plotly/dash-table/issues/776

I can reproduce this after resizing my window, however I can't reproduce it on first draw. A user from the community can though:

https://community.plotly.com/t/dash-1-12-datatable-format-issues-when-using-fixed-header/39120

![image](https://user-images.githubusercontent.com/1280389/81458558-d9c17680-914f-11ea-8cdb-90a202c5ed8f.png)

**Comment by chriddyp** [comment]
As per the community member, this is indeed a regression:

> Indeed the bug is exclusive to Dash 1.12. Ran the same code with Dash 1.11 and the format looks correct:


![image](https://user-images.githubusercontent.com/1280389/81460139-43458300-9158-11ea-8847-efe9d56c0f02.png)


So, we'll need to fix this in a patch release @Marc-Andre-Rivet

**Comment by chriddyp** [comment]
I see this in the dash-docs Percy images too
![image](https://user-images.githubusercontent.com/1280389/81988475-63f65880-95f0-11ea-8454-52555e5e05ba.png)

**Comment by noisycomputation** [comment]
The header row also fails to scroll horizontally when fixed_rows is True, I reported this in #746 but wanted a cross-reference here since the bug straddles these two issues (and peripherally some others as well). As I noted in #746, the buggy behavior can be seen on the documentation pages.

**Comment by michaelbabyn** [comment]
Another issue that came up in 1.12.0 was that when there are a lot of columns and horizontal scrolling is necessary the data cells scroll but the headers don't.
```python
import dash
import dash_table
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

app = dash.Dash(__name__)

app.layout = dash_table.DataTable(
    columns=[{"name": i, "id": i} for i in list(df.columns) * 3],
    data=df.to_dict('records'),
    fixed_rows={'headers': True},
    style_cell={'minWidth': '180px', 'width': '180px', 'maxWidth': '180px'},
)

if __name__ == '__main__':
    app.run_server(debug=True, port=8022)
```

![Peek 2020-05-14 18-05](https://user-images.githubusercontent.com/41019918/81990654-92366100-960d-11ea-9fb3-478e06dd9875.gif)

**Comment by adrianoesch** [comment]
ran into the same issue (header not aligned). a simple ` window.dispatchEvent(new Event('resize'));` does the trick for me.

**Comment by michaelbabyn** [comment]
Note @plotly/dash , as of today this bug is affecting a Dash Enterprise customer
