### ISSUE TITLE
Native filter does not work with pagination after page 0

### ISSUE THREAD

**Issue by shieldofchaos** [plotly/dash-table#782]
Greetings. It seems like there is a bug with native filtering when it is used on the datatable with pagination after page 1. The datatable documentation version works but it could be due to custom filtering?

Please see this gif below:
![ezgif-2-2114c5eb4d6a](https://user-images.githubusercontent.com/37095549/82719817-92ef8700-9ce0-11ea-9136-2279d6afd8de.gif)

It is rather small to see but basically when I am in page 2 and type "Cal" or "Texas", the datatable returns empty (even when Texas is in page 2). This has been tested on a larger dataset and the same issue occurs.

Below is the full sample code that replicate this issue:

```
import dash
import dash_table
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

app = dash.Dash(__name__)

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict('records'),
	filter_action="native", 
	row_selectable="multi",
	page_action="native", 
	page_current=0,
	page_size=5,
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by pvtodorov** [comment]
same issue. is this going to be resolved?

**Comment by tuan-gnu** [comment]
I've got same issue today. 
I try to make a small callback to make the page to 0 when filter and it works. Hope that it will help.

@app.callback(
    Output('table', "page_current"),
    Input('table', "filter_query"))
def update_table(filter):
    return 0
