### ISSUE TITLE
Copy & paste when clicking to select cells doesn't work anymore?

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-table#790]
Originally reported in https://community.plotly.com/t/copying-from-datatable/40571/3.

It seems like it works when you use the keyboard to navigate and select cells (shift + arrow keys) but it doesn't work for me if I use the mouse to select cells: shift + click.

I believe this worked in the past.

Here's a GIF to reproduce. Taken from https://dash.plotly.com/datatable

![copy-paste](https://user-images.githubusercontent.com/1280389/83906394-59733e80-a718-11ea-88a6-139d53261b5d.gif)

**Comment by jko14** [comment]
Hi @chriddyp  - thanks so much for looking into this! I've also noticed that items that are copy/pasted from the table get "stuck" on the clipboard, so that you can no longer copy addition info from the table unless you reload the page - if you look at the version in your gif, the same bug I'm experiencing is demonstrated (e.g. the selection starting with "Nevada" was pasted both times)

**Comment by mhnrchs** [comment]
I'm seeing this exact same issue again in dash-table 4.11.3 (dash 1.20.0). I am also using the first example on https://dash.plotly.com/datatable and seeing the same results @chriddyp showed in his GIF above.

Can anyone confirm and re-open this issue?

**Comment by ChristianJuhl** [comment]
I can confirm this issue with dash-table 4.11.3. Would be really nice to get it fixed.

**Comment by emiliobasualdo** [comment]
Same here

- Can not copy when selected with shift-mouse
- Can only copy 1 time with shift-arrow, then I have to refresh the page.

dash==1.20.0
dash-bootstrap-components==0.12.2
dash-core-components==1.16.0
dash-html-components==1.1.3
dash-renderer==1.9.1
dash-table==4.11.3
Flask==2.0.1

**Comment by audreybreitwieser** [comment]
+1, would love to get this fixed!

**Comment by ChristianJuhl** [comment]
> I can confirm this issue with dash-table 4.11.3. Would be really nice to get it fixed.

BUMP

**Comment by MoayyadKishkieh** [comment]
had the same issue (for both mouse and arrow keys)
I added this to `dash_table.DataTable` properties:

`include_headers_on_copy_paste = 'True' ` 

and somehow everything worked fine 

when having multiple tables make sure to give them unique IDs

**Comment by gershonavi** [comment]
Hi I still can not copy cell content. is there any progress on this ?
