### ISSUE TITLE
Space as thousand separator for non English country 

### ISSUE THREAD

**Issue by pauostr** [plotly/dash-table#832]
Hi there, 

Is it possible to add the possibility to use a space for thousand separator instead of a coma? Many country use space as radix characters ... I saw that in the Format class there is no option other than '' or ',' for it, could you add the possibility to choose between ',' and ' ' ? 

Thx

**Comment by Batalex** [comment]
Hi,
you can use the `Format` class

```python
from dash_table.Format import Format, Group

fmt = Format(
    group=Group.yes,
    groups=3,
    group_delimiter=" ",
    decimal_delimiter=",",
)
```

and then apply this `fmt` to each column.

Good luck!

**Comment by pauostr** [comment]
Thx it works!
