### ISSUE TITLE
React Warning "each child should have a unique "key" prop

### ISSUE THREAD

**Issue by bjonen** [plotly/dash-table#860]
When running the basic table example from https://dash.plotly.com/datatable, there is warning in the console: 

```
Warning: Each child in a list should have a unique "key" prop
```

I am running dash inside docker with versions: 
dash: 1.18.1
dash-table: 4.11.1

**Comment by xwk** [comment]
Seems to be duplicate of https://github.com/plotly/dash/issues/1433
