### ISSUE TITLE
Links in cell change table layout.

### ISSUE THREAD

**Issue by audetto** [plotly/dash-table#914]
Using 
dash-table 4.11.2

I have followed the advice on forum and here https://github.com/plotly/dash-table/issues/222

to use markdown to create links in cells.

Problem is that the whole table changes layout when a column is market as markdown.
In particular each link is surrounded by `<p>` which causes rows to take more vertical space.

Is there a way to avoid this side effect?

**Comment by AnnMarieW** [comment]
Hi @audetto 

You can change the margin on the `<p>` element by using the table's `css` prop.  For example:
`css=[dict(selector='p', rule='margin: 0px;')],`

Or you can  include a css file in the app’s /assets folder.  See more info on that [here](https://dash.plotly.com/external-resources).

**Comment by audetto** [comment]
Yes, this is good, and more localised.
Thank you.
