### ISSUE TITLE
Allow HTML content in Markdown cells

### ISSUE THREAD

**Issue by mjanschek** [plotly/dash-table#915]
**Context**

```
dash                      1.20.0
dash-bootstrap-components 0.12.2
dash-core-components      1.16.0
dash-html-components      1.1.3 
dash-renderer             1.9.1 
dash-table                4.11.3
```

**Describe the bug**

I am not sure, if this is a bug or intended behaviour.
A Datatable column that presents Markdown can't render html snippets. In this case, I try to include an icon from the bootstrap font.

**Expected behavior**

A Data Table that present Markdown should be able to render html code, as it's encouraged by [Markdown guidelines](https://daringfireball.net/projects/markdown/syntax#html). If I directly edit the websites html, the icon can be displayed. So the font is included correctly.

**Minimal example**

app.py
```
import dash
import dash_table

bs_icons = {
    "href": "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css",
    "rel": "stylesheet",
    "crossorigin": "anonymous",
}

app = dash.Dash(__name__, external_stylesheets=[bs_icons])

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"name": "Alarm", "id": "html", "presentation": "markdown"}],
    data=[{"html": '<i class="bi bi-alarm"></i>'}],
)

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Screenshots**
Original Table
![image](https://user-images.githubusercontent.com/1671175/122730074-209dfd00-d27a-11eb-96c4-1d462663e96b.png)
Edited Table (wanted result)
![image](https://user-images.githubusercontent.com/1671175/122730278-5642e600-d27a-11eb-9bea-bb547ba603fc.png)

**Comment by alexcjohnson** [comment]
(moved to the table repo and recast as a feature request)

Dash-table uses [Remarkable](https://www.npmjs.com/package/remarkable) for its markdown, and by default Remarkable [disables HTML input](https://www.npmjs.com/package/remarkable#constructor). I presume this is for security reasons, as untrusted HTML input often creates XSS vulnerabilities. We would, however, be comfortable exposing the ability to enable HTML input on an opt-in basis. This may be as simple as adding `html` to the [`markdown_options` prop](https://github.com/plotly/dash-table/blob/1e016de2dccda99bfefb100eb13a518af17af425/src/dash-table/dash/DataTable.js#L477-L487) and the [corresponding interface](https://github.com/plotly/dash-table/blob/1e016de2dccda99bfefb100eb13a518af17af425/src/dash-table/components/Table/props.ts#L164-L166), if someone would like to create a PR to try it!

**Comment by mjanschek** [comment]
@alexcjohnson thank you so much for considering this!

**Comment by AnnMarieW** [comment]
Hey @alexcjohnson  - Thanks for the pointers - that worked great!  :cake: 
 I'll do a PR.

![image](https://user-images.githubusercontent.com/72614349/123639941-8556db80-d7d5-11eb-946a-58e5da9da8d6.png)
```
import dash
import dash_table

bs_icons = {
    "href": "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css",
    "rel": "stylesheet",
    "crossorigin": "anonymous",
}

app = dash.Dash(__name__, external_stylesheets=[bs_icons])

app.layout = dash_table.DataTable(
    id="table",
    columns=[{"name": "Alarm", "id": "html", "presentation": "markdown"}],
    data=[{"html": '<i class="bi bi-alarm"></i>'}, {"html": '<i class="bi bi-emoji-sunglasses"></i>'}],
    markdown_options={"html": True},
)

if __name__ == "__main__":
    app.run_server(debug=True)


```

**Comment by prhbrt** [comment]
Quick note, also link_target as discussed [here](https://dash.plotly.com/dash-core-components/markdown) works now.

    markdown_options={"html": True, "link_target": "_self"},
