### ISSUE TITLE
Old pycodestyle package cause an error while installing packages

### ISSUE THREAD

**Issue by bitsnaps** [plotly/dash-table#920]
Hello,

We've been trying to recompile dash from the source, and we realized that `pycodestyle` [used](https://github.com/plotly/dash-table/blob/2d33ef7dae176d7b3c7032ca520ccb79202d1adf/requirements.txt#L38) in this repo is outdated, which cause a pip (python 3.8) error during the installation:
```
autopep8 1.5.7 requires pycodestyle>=2.7.0, but you have pycodestyle 2.6.0 which is incompatible
```
Steps to reproduce:
1- Clone the repo:
```
git clone --depth 1 https://github.com/plotly/dash-table.git
``` 
2- Rebuild and compile:
```
cd dash-table && npm ci && npm run build && python setup.py sdist && mv dist/* ../packages/ && cd ..
```
Upgrading `pycodestyle` to `2.7.0` won't cause any issue, you can check this [fork](https://github.com/CorpoSense/dash) to reproduce the issue on [Gitpod](https://gitpod.io/) (checkout `.gitpod.yml` for rebuild instructions).

**Comment by alexcjohnson** [comment]
Thanks @bitsnaps - I don't see any errors when I follow your steps, but perhaps you're also doing `pip install -r requirements.txt` somewhere in there, as mentioned in the rather outdated [CONTRIBUTING.md](https://github.com/plotly/dash-table/blob/dev/CONTRIBUTING.md)? I think we should actually delete `requirements.txt` and `python-requirements.txt`, these are unused. On CI we use `dev-requirements.txt` plus `dash[dev,testing]`

**Comment by bitsnaps** [comment]
@alexcjohnson That's possibly the issue, it looks like something went wrong with some pip packages, the error doesn't appear anymore, I've just compiled successfully dash-table on newly created [branch](https://github.com/bitsnaps/dash-table/tree/gitpod-setup) along with gitpod config and updated [CONTRIBUTING.md](https://github.com/bitsnaps/dash-table/blob/gitpod-setup/CONTRIBUTING.md) if you accept PR.
