### ISSUE TITLE
Include option rowReorder

### ISSUE THREAD

**Issue by georgeblck** [plotly/dash-table#952]
Hello,

I am trying to use the possibility to drag-and-drop rows that is usually supported by DataTables and it is not working.

This is the simple code snippet that would activate it:

```js
$(document).ready(function() {
    var table = $('#cell-table').DataTable( {
        rowReorder: true
    } );
} );
```

For more information see [here](https://datatables.net/extensions/rowreorder/examples/initialisation/simple.html)

**Comment by alexcjohnson** [comment]
This repo is for Dash DataTable https://dash.plotly.com/datatable - a different project from the jQuery plugin you're referring to.

**Comment by georgeblck** [comment]
Oh sorry, I was sure that this Project built on the jQuery plugin because they shared the name.
